### ISSUE TITLE
example

### ISSUE THREAD

**Issue by chenggaogc** [ucsb-seclab/agrigento#1]
Can you provide an example of each plugin?

**Comment by conand** [comment]
Can you elaborate a bit more? What do you mean exactly?

**Comment by pyretta** [comment]
Hi. I think chenggaogc meant something like "could you please offer sample APK files?". I would also appreciate it if you would offer sample APK files of the apps "changer" and "crypto-hooker". Your Android Studio projects cannot be built as APK. I have tried several times with the latest version of Android Studio (3.5.2). Below the menu item "built" there is no option to create an APK for your projects. They also contain errors. Both apps contain 3 errors in styles.xml and 4 errors in AndroidManifest.xml. 
I really would like to test your tool "agrigento". Already installed the programm on Ubuntu. Only these apps for android are still missing.

Thank you very much in advance.

**Comment by conand** [comment]
Hi, APKs for changer and crypto-hooker have been added (`changer/app/build/outputs/apk/app-debug.apk` & `crypto-hooker/app/build/outputs/apk/app-debug.apk`). Please, check your Android Studio configuration, it is very weird that you do not find any option to build APKs.

Cheers!
